-- DDL generated by Postico 1.4.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE if not exists provision (
    bucketname text PRIMARY KEY,
    location text,
    accesskey_enc text,
    secretkey_enc text,
    billingcode text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX if not exists provision_pkey ON provision(bucketname text_ops);
